type Bin={id:string;location:string;fill:number;temp:number;battery:number};
const bins:Bin[]=[{id:"SW-204",location:"Market Road",fill:94,temp:31,battery:87},{id:"SW-118",location:"Lake View",fill:81,temp:29,battery:91},{id:"SW-077",location:"Central Park",fill:67,temp:30,battery:76},{id:"SW-311",location:"Tech District",fill:46,temp:27,battery:42},{id:"SW-052",location:"Bus Stand",fill:88,temp:32,battery:63}];
const $=<T extends HTMLElement>(s:string)=>document.querySelector(s) as T;
const toast=(m:string)=>{const t=$<HTMLDivElement>("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
function renderBins(){ $("#binTable").innerHTML=bins.map(b=>`<tr><td><b>${b.id}</b></td><td>${b.location}</td><td><div class="fill"><i style="width:${b.fill}%"></i></div><b>${b.fill}%</b></td><td>${b.temp}°C</td><td>${b.battery}%</td><td><span class="badge ${b.fill>=85?"danger":b.fill>=70?"warning":"ok"}">${b.fill>=85?"OVERFLOW RISK":b.fill>=70?"HIGH":"NORMAL"}</span></td></tr>`).join("");$("#mRisk").textContent=String(bins.filter(b=>b.fill>=85).length);$("#mBins").textContent=String(bins.length+123)}
function renderAlerts(){ $("#alerts").innerHTML=bins.filter(b=>b.fill>=80).map(b=>`<div class="alert"><span class="dot ${b.fill>=90?"red":""}"></span><div><b>${b.id} — ${b.location}</b><small>${b.fill}% full · collection recommended</small></div><strong>${b.fill}%</strong></div>`).join("")||"<p>No priority alerts.</p>"}
function renderRoutes(){const s=[...bins].sort((a,b)=>b.fill-a.fill);$("#routeCards").innerHTML=s.map((b,i)=>`<article class="route"><div class="routeicon">T-${String(i+4).padStart(2,"0")}</div><div><b>Priority ${i+1} · ${b.id}</b><p>${b.location} → ${b.fill}% full · estimated ${Math.max(18,55-i*7)} min</p></div><span>${Math.round(b.fill*.9)} pts</span></article>`).join("")}
function drawChart(){const c=$("#trend") as HTMLCanvasElement,x=c.getContext("2d")!,W=c.clientWidth,H=150;c.width=W*2;c.height=H*2;x.scale(2,2);const v=[10,13,12,17,15,21,24];x.lineWidth=3;x.beginPath();v.forEach((n,i)=>{const px=12+i*(W-24)/6,py=H-15-n/25*(H-30);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();v.forEach((n,i)=>{const px=12+i*(W-24)/6,py=H-15-n/25*(H-30);x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fill()})}
document.querySelectorAll<HTMLButtonElement>(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));$<HTMLElement>(`#${b.dataset.section}`).classList.add("active");$("#pageTitle").textContent=b.textContent!.replace(/^[^A-Za-z]+/,"")});
$("#refresh").onclick=()=>{bins.forEach(b=>b.fill=Math.min(99,Math.max(15,b.fill+Math.random()*6-1)));renderBins();renderAlerts();renderRoutes();toast("IoT telemetry refreshed")};
$("#addBin").onclick=()=>{bins.push({id:`SW-${String(320+bins.length).padStart(3,"0")}`,location:"New Demo Zone",fill:Math.round(35+Math.random()*50),temp:28,battery:100});renderBins();renderAlerts();renderRoutes();toast("Demo smart bin registered")};
$("#optimize").onclick=()=>{renderRoutes();toast("Java route optimization simulated")};$("#report").onclick=()=>toast("Operational report generated");setInterval(()=>$("#clock").textContent=new Date().toLocaleTimeString(),1000);renderBins();renderAlerts();renderRoutes();drawChart();window.addEventListener("resize",drawChart);